version: "3.8"

services:
  app:
    build:
      context: .
#                    беремоо інфу про систему із докерфайлу
    volumes:
#                    підключаємо стор з нашого комп'ютра
      - ./backend:/app
#                     вказуємо шлях звідки беремо дані та чанез : вказуємо де будуть на віртуальному
      - /app/node_modules
#                    вказуємо папу ноде модулів щоб вони не копіювалися з локальної машини, вона не буде дублюватися
    restart: on-failure
#                     вказуємо коли буде рестарт машини - при помилці
    env_file:
      - .env
    command: >
      sh -c "npm start"
#      sh -c "node index.js" - прописуємо команду на запуск, в пекеджі я маю скрипт на старт

    ports:
      - "5000:5000"
# пишемо порт по якому ми хочемо мати доступ та відповідний порт на стороні докера (порт в докері ми прописували)
#  при підключенні через веб порт не потрібно відкривати


  db:
    image: mongo
#    сервер на якому буде стартувати, скачується з докер хабу
    env_file:
      - .env
    volumes:
      - ./mongo_db:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
#                   файл ініціалізації кладемо за шляхо та в кінці через : пишемо :ro - рід онлі
    restart: on-failure
    ports:
      - "27017:27017"
# пишемо порт по якому ми хочемо мати доступ та відповідний порт на стороні докера (порт в докері ми прописували)

  web:
    image: nginx:alpine
#    сервер на якому буде стартувати, скачується з докер хабу
    ports:
      - "80:80"
    restart: on-failure
    volumes:
      - ./client:/usr/share/nginx/html
# звідки беремо зкомпілені файли та куди кладемо
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
# звідки беремо файл конфігурації